services:
  api:
    build: .
    ports:
      - "8000:8080"
    environment:
      - SECRET_KEY=please-change
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
      # For Postgres, uncomment and set:
      # - DATABASE_URL=postgresql+psycopg2://user:password@db:5432/app
    volumes:
      - ./:/app
  # db:
  #   image: postgres:16
  #   environment:
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: app
  #   ports:
  #     - "5432:5432"
